[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.1"


[context.production.environment]
   HUGO_VERSION = "0.55.1"


[[redirects]]
  from = "tags/english"
  to = "en"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["en"]}